### ISSUE TITLE
Some question within reading the Readme

### ISSUE THREAD

**Issue by cookiegg** [mveres01/grasping#1]
Dear mveres01,
  I have some questions when reading and executing your code.
during **step1**, you said 
```
$: cd initialize
$: python prepare_meshes.py
```
Maybe it's mean 
```
$: cd initialize
$: python prepare_mesh.py
```
because there is no  `prepare_meshes.py`  in your repository but `prepare_mesh.py`.

And another question: I don't understand the meaning of follow sentence:
>Run initialize/prepare_candidates.py. This will read the pose information collected by V-REP, and generate a list of candidates for each object that will be tested in the simulator. Note that these candidates will be saved under collect/candidates
 >```
>$: cd initialize
>$: cat ../data/initial_poses.txt | parallel python prepare_meshes.py
>```

Does it's meaning we should run the following code
```
$: cd initialize 
$: python prepare_candidates.py
$: cat ../data/initial_poses.txt | parallel python prepare_meshes.py
```

Can you give me some tips? Thanks a lot!

**Comment by mveres01** [comment]
Thanks for catching this, I forgot to update the README about the changed filename. The first command should read: 

`$: cd initialize`
`$: python prepare_mesh.py`

The second snippet of code should be:

`$: cd initialize`
`$: cat ../data/initial_poses.txt | parallel python prepare_candidates.py`

**Comment by cookiegg** [comment]
thanks !
