### ISSUE TITLE
vrep error

### ISSUE THREAD

**Issue by cookiegg** [mveres01/grasping#2]
Dear mveres01, when I run 
```
cat commands/main1.txt |parallel -j 16
```
get the error message as following:
```
/bin/bash: vrep.sh: command not found
```
And if I replace the code in `main0.txt`:
```
ulimit -n 4096; export DISPLAY=:1; vrep.sh -h -q -s -g40_carafe_final-11-Mar-2016-17-09-17.txt -g1 -g1501 /home/forrest/robo/grasping/collect/scene_collect_grasps.ttt 
```
with
```
ulimit -n 4096; export DISPLAY=:1; /home/forrest/robo/V-REP_PRO_EDU_V3_4_0_Linux/vrep.sh -q -s -g40_carafe_final-11-Mar-2016-17-09-17.txt -g1 -g1501 /home/forrest/robo/grasping/collect/scene_collect_grasps.ttt
```
i.e.,I set the absolute path of vrep. But I just get another error:
```
QXcbConnection: Could not connect to display :1
/home/forrest/robo/V-REP_PRO_EDU_V3_4_0_Linux/vrep.sh: line 33: 15247 Aborted                 (core dumped) "$dirname/$appname" "${PARAMETERS[@]}"
```
And I have read the [Trouble running V-REP headless](http://www.forum.coppeliarobotics.com/viewtopic.php?t=6546) in V-REP forum, but don't know how to deal with it.
Could you give me some suggestion about this problem? thanks!

**Comment by ashleylid** [comment]
I have had issues like this before. It's with the XServer/display, V-REP tends to be funny with how you call displays, its like when you have too many running, or you are porting through a number of tunnels it won't allow connection to the XServer for too many instances. You need to try a bunch of things. It's not necessarily the headless mode that's the issue. 

- Try being in the V-REP folder from the start. 

- You don't have the -h option, where do you say that you are in headless mode? 
See this link: [command line for V-REP](http://www.coppeliarobotics.com/helpFiles/en/commandLine.htm). Also, keep to how they do the statements - in that order. (eg ./vrep.sh -h -s5000 -q myScene.ttt) 
- Try also not setting the DISPLAY tag, is there a reason you need this? How many displays are you running? How many instances of V-REP - this may also be the issue - At least it was for me.

**Comment by mveres01** [comment]
If you haven't installed V-REP globally, or your OS can't find it, setting the absolute path to V-REP works as well.

@kleinash is right, that error you're getting seems to be a problem with the Xserver (or lack thereof). We used [Xorg](https://wiki.archlinux.org/index.php/xorg), which IIRC is needed for rendering the vision elements while in headless mode. When we originally ran our experiments, we were running using clusters of mutiple GPU's, and each had its own Xserver, which we indexed by the `export DISPLAY=:1` line. But I agree this is confusing, and I'll update the README!

If you don't want to run in headless mode, you should be able to run with the command:

```
/home/forrest/robo/V-REP_PRO_EDU_V3_4_0_Linux/vrep.sh -q -s -g40_carafe_final-11-Mar-2016-17-09-17.txt -g1 -g1501 /home/forrest/robo/grasping/collect/scene_collect_grasps.ttt
```

If you still have problems running in headless mode after installing the Xserver, let me know and I'll see if I can find the instructions we used.

**Comment by mveres01** [comment]
Doesn't seem to be any activity on this, so I'm closing it. Let me know if there's still any issue.
